### ISSUE TITLE
[F#] Create computation expressions for ViewBuilder

### ISSUE THREAD

**Issue by chkn** [chkn/Xamarin.SwiftUI#24]
Inspired by the C# syntactic sugar in [SwiftUI.Views](https://github.com/chkn/Xamarin.SwiftUI/blob/master/src/SwiftUI/SwiftUI/Views.cs), we should add an F# library with a module of the same name that has a computation expression builder to implement the forms with `[ViewBuilder]` arguments.

All members should be `inline` and we should define a [LinkerSafeAttribute](https://docs.microsoft.com/en-us/dotnet/api/foundation.linkersafeattribute?view=xamarin-ios-sdk-12) and mark the assembly with it. The F# compiler is pretty good at inlining computation expressions, so this should result in this entire library being linked out.

**Comment by 7sharp9** [comment]
I think open a static is in F#5, I not sure a button or view CE would be a good idea.

What would the syntax look like and how would it be better than a plain old static method with optional params?

**Comment by chkn** [comment]
Hmm maybe we have static methods that return a CE?

The problem to solve is container views. Views in SwiftUI are immutable structs, so it builds up a container view using [ViewBuilder](https://developer.apple.com/documentation/swiftui/viewbuilder), which is actually very close to the Swift equivalent of a computation expression.

For example, take this Swift code snippet:

```
VStack {
	Text("foo")
	Button(action: { }) {
		Image("icon")
		Text("CLICK ME")
	}
	Spacer()
}
```
The above would generate a value of the type:
```
SwiftUI.VStack<SwiftUI.TupleView<(SwiftUI.Text, SwiftUI.Button<SwiftUI.TupleView<(SwiftUI.Image, SwiftUI.Text)>>, SwiftUI.Spacer)>>
```

To make matters worse, to do proper interop with Swift, we need to staticly know the exact type of body a custom view would return. This is the reason that our `View` abstract class doesn't declare an abstract `Body` property to override, but instead uses reflection to find it--F#'s type inference wouldn't automatically set the proper return type if you are overriding a base member.

**Comment by 7sharp9** [comment]
It kind of sounds similar to the issue with Fleece and Falanx:

https://github.com/jet/falanx/blob/master/src/Falanx.Proto.Core/JsonCodec/Codec.fs#L756-L775

Where in normal F# code and the usage of applicatives everything is inferred, but with code generation you need to know the final type which is based on the appending of generic types in the expression.  For the example about its done around here:  https://github.com/jet/falanx/blob/master/src/Falanx.Proto.Core/JsonCodec/Codec.fs#L342-L391

Which was a ind bender to get right.   If did allow you to write code like:

```fsharp
type unionWithOperators =
    | Foo_int of Foo_int : int
    | Foo_string of Foo_string : string
    | Foo_message of Foo_message : TestAllTypes
    static member JsonObjCodec =
        jchoice
            [
                Foo_int     <!> jreq "Foo_int"     (function Foo_int     x -> Some x | _ -> None)
                Foo_string  <!> jreq "Foo_string"  (function Foo_string  x -> Some x | _ -> None)
                Foo_message <!> jreq "Foo_message" (function Foo_message x -> Some x | _ -> None)
            ]
```

Where `JsonObjCodec` method defined both the encoding and decoding properties of the `unionWithOperators`

**Comment by 7sharp9** [comment]
```fsharp
type Shape with
        static member JsonObjCodec =
            jchoice
                [
                    Rectangle <!> jreq "rectangle" (function Rectangle (x, y) -> Some (x, y) | _ -> None)
                    Circle    <!> jreq "radius"    (function Circle x -> Some x | _ -> None)
                    Prism     <!> jreq "prism"     (function Prism (x, y, z) -> Some (x, y, z) | _ -> None)
                ]

let shapeEncoded = Codec.encode myShape
let shapeDecoded = Codec.decode shapeEncoded
```

The Codec.encode/decode know how to do all of the work based on SRTP resolution.   Not sure if it would work this way, it feels similar though...

**Comment by chkn** [comment]
Oh that's interesting! Kinda makes me think of https://github.com/chkn/SharpBoomerang. I'm not quite sure what you're suggesting though.

I played around in SharpLab, and this contrived code pretty much works..
```fsharp
type EmptyView() = class end
type TupleView<'x,'y>(x : 'x, y : 'y) = class end
type Text(txt:string) = class end
type Button<'t>(action, label : 't) = class end

type ViewBuilder() =
    member inline __.Zero() = EmptyView()
    member inline __.Yield(x) = x
    member inline __.Combine(x, y) = TupleView(x, y)
    member inline __.Delay(fn) = fn()

type ButtonBuilder(action) =
    inherit ViewBuilder()
    member __.Run(view) = Button(action, view)

type Views =
    static member inline Button(action) = ButtonBuilder(action)

module Foof =

    let view() =
        Views.Button(fun () -> printfn "hi") {
            Text("Hello")
            Text("hi")
        }
```

This composes the views correctly, but it's a shame there's no way to inline the constructor/action field:

```csharp
public static Button<TupleView<Text, Text>> view()
        {
            ButtonBuilder buttonBuilder = new ButtonBuilder(new view@22());
            Text x = new Text("Hello");
            Text y = new Text("hi");
            TupleView<Text, Text> label = new TupleView<Text, Text>(x, y);
            return new Button<TupleView<Text, Text>>(buttonBuilder.action, label);
        }
```

This is what I really want to see:

```csharp
public static Button<TupleView<Text, Text>> view()
        {
            Text x = new Text("Hello");
            Text y = new Text("hi");
            TupleView<Text, Text> label = new TupleView<Text, Text>(x, y);
            return new Button<TupleView<Text, Text>>(new view@22(), label);
        }
```

**Comment by 7sharp9** [comment]
@chkn Whats the syntactic sugar in C# that allows this the list constructor syntax?

**Comment by 7sharp9** [comment]
@gusty SRTP could build up these generics if Im thinking correctly?

**Comment by Thorium** [comment]
> This is what I really want to see

A bit hack but could you do that by overriding implicit cast operator?

**Comment by sandeep-eroad** [comment]
Have a look at https://github.com/Zaid-Ajaj/fabulous-simple-elements

This is what I am using in my Fabulous app.

**Comment by chkn** [comment]
@Thorium Not sure I follow. I thought implicit casts don't work in F#?

@7sharp9 For C#, I'm using the new Source Generators feature that's in preview. My source generator walks the Roslyn AST and transforms lambdas in a very similar way to F# CEs. See https://github.com/chkn/Xamarin.SwiftUI/pull/19/files#diff-2d195671e7f17d9ea2bf102c39e5375fR14

So you could write C# code like:

```csharp
public View Body =>
    Button (() => Console.WriteLine("You clicked me"), () => {
        Text ("Hello");
        Text ("World");
    });
```

And it would be translated by the source generator to something like:

```csharp
public Button<TupleView<Text,Text>> Body =>
    Button (() => Console.WriteLine("You clicked me"), new TupleView<Text,Text> (Text ("Hello"), Text("World")));
```

@sandeep-eroad The problem is that we need to staticly declare the exact return type of the `Body` property, such as in the snippet directly above. See https://github.com/chkn/Xamarin.SwiftUI/issues/24#issuecomment-641067681

**Comment by 7sharp9** [comment]
@chkn I mean we could do something similar with Myriad, it's sort of the equivalent of source generators but for F#, more strongly typed AST construction wise.

**Comment by Thorium** [comment]
@chkn what I meant is:
```c#
ButtonBuilder buttonBuilder = new ButtonBuilder(new view@22());
return new Button<TupleView<Text, Text>>(buttonBuilder.action, label);
```
This is C# right? So if you define implicit_op in F# side, the C# code can call it.  If you make the types as
```fsharp
type Button<'t>(action, label : 't) = ...
and ViewBuilder() = ...
and ButtonBuilder(action) = ...
```
...you can either add a new consturctor to the Button or the implicit cast, to inline the constructor/action field of the ButtonBuilder.

*Edit: Sorry, this went off-topic.*

**Comment by 7sharp9** [comment]
@Thorium The essence of the problem is trying to make an F# solution thats as elegant as the C#/Swift mechanisms.

**Comment by sandeepc24** [comment]
![image](https://user-images.githubusercontent.com/4897654/84494388-836ec700-acfd-11ea-8a62-1fa86a02d6d0.png)


Here is the screenshot of what I had asked about last month. I am not sure if it is possible or not but I was thinking of using F# to generate an output similar to XAML and then the rest of VS tool chain should be able to work with it(over simplified :-)).

**Comment by chkn** [comment]
@7sharp9 FYI- this is basically what I wanted to do with the CE: https://github.com/chkn/Xamarin.SwiftUI/pull/37
