### ISSUE TITLE
Try and make the F#/C# examples are similar in functionality as possible, currently they are not entirely the same.

### ISSUE THREAD

**Issue by 7sharp9** [chkn/Xamarin.SwiftUI#30]

**Comment by CartBlanche** [comment]
@7sharp9 I've mainly worked on the C# samples 1st, hence why they are slightly ahead of the F# examples. My most recent PR was to use a shared project between iOS and Mac, but we could make that a shared assembly, if there is an elegant way to doing it for both C# and F#.

**Comment by 7sharp9** [comment]
F# can reference a C# assembly.  Shared project are uni-language unfortunately, I added them to F# back at Xamarin but it was not easily possible make F# invoke the C# compiler and vice versa on the msbuild targets.

**Comment by chkn** [comment]
Closing in favor of #34
