### ISSUE TITLE
Error : If you are building projects that require targets from full MSBuild or MSBuildFrameworkToolsPath, you need to use desktop msbuild ('msbuild.exe') instead of 'dotnet build' or 'dotnet msbuild

### ISSUE THREAD

**Issue by 7sharp9** [chkn/Xamarin.SwiftUI#31]
Full error:
```
.nuget/packages/msbuild.sdk.extras/2.0.54/Build/Workarounds.targets(27,5): error : If you are building projects that require targets from full MSBuild or MSBuildFrameworkToolsPath, you need to use desktop msbuild ('msbuild.exe') instead of 'dotnet build' or 'dotnet msbuild' [Xamarin.SwiftUI/src/SwiftUI/SwiftUI.csproj]
```

So does this mean mono must be installed on macOS?

**Comment by chkn** [comment]
It should theoretically be possible to build just the netstandard version with .NET Core without mono installed. I haven’t tried it, but I think the tests basically do this.

You might try something like:
`dotnet build -p:TargetFrameworks=netstandard2.1`

**Comment by 7sharp9** [comment]
I could build with VS4M but not with the botnet build mentions din the readme.

**Comment by chkn** [comment]
Well the readme mentions using `msbuild build.proj` which is basically like a build-the-world thingy. But I think `dotnet build` should work directly within the `src/SwiftUI` directory

**Comment by chkn** [comment]
Closing, as I think the comments address the issue. Feel free to reopen if not.
