### ISSUE TITLE
F# sample is a little mangled

### ISSUE THREAD

**Issue by 7sharp9** [chkn/Xamarin.SwiftUI#32]
<img width="252" alt="Screenshot 2020-06-23 at 23 18 43" src="https://user-images.githubusercontent.com/588746/85471113-e850d980-b5a7-11ea-9e1c-f400592a1cc0.png">

Not running in the iOS simulator either

**Comment by 7sharp9** [comment]
My mistake, this is running as a macOS app.  Still mangled.

**Comment by chkn** [comment]
Same answer as https://github.com/chkn/Xamarin.SwiftUI/issues/33#issuecomment-650271024

These “samples” are more like for exercising the code at this point, and aren’t actually good examples of how you should use the framework

**Comment by chkn** [comment]
Closing in favor of #34
