### ISSUE TITLE
XamariniOSSwiftUITest is mangled when running.   

### ISSUE THREAD

**Issue by 7sharp9** [chkn/Xamarin.SwiftUI#33]
<img width="396" alt="Screenshot 2020-06-23 at 23 20 17" src="https://user-images.githubusercontent.com/588746/85471279-1f26ef80-b5a8-11ea-95fd-16e2522eabd8.png">

**Comment by 7sharp9** [comment]
It just occurred to me that maybe this is what its supposed to look like though?

**Comment by chkn** [comment]
Hah yeah I believe that’s “by design” .. we were trying to exercise all the things we’ve bound and weren’t paying too much attention to how it looks 😜
