### ISSUE TITLE
Even length namespace and class names cause crash

### ISSUE THREAD

**Issue by chkn** [chkn/Xamarin.SwiftUI#35]
Definitely sounds like something weird is going on. We could clone the Swift source and try to catch the crash in the debugger

_Originally posted by @chkn in https://github.com/chkn/Xamarin.SwiftUI/pull/28#issuecomment-653702689_

**Comment by CartBlanche** [comment]
@chkn I asked Steve if he'd heard of or come across this and he mentioned the following...

> If I were to guess what’s going on I’d say that there’s an issue in encoding the class names from .NET into C# in the type metadata.
> 
> There are two types of encodings that happen - one is for the actual name which should go into UTF8 and is unlikely to be the problem, but it might be that there are symbols being generated that need to be in punycode and there’s an issue in the punycode encoder.
