### ISSUE TITLE
I have an Android connection VPN code. After binding, if there is no connection status event, can you bind it for me?

### ISSUE THREAD

**Issue by bbhxwl** [chkn/Xamarin.SwiftUI#44]
I have an Android connection VPN code. After binding, if there is no connection status event, can you bind it for me?

**Comment by chkn** [comment]
I'm not sure what your request is about. This repo is a binding of SwiftUI for Apple platforms. There is no support for Android and nothing related to VPNs

**Comment by chkn** [comment]
Closing as off topic
