### ISSUE TITLE
Target .NET 6 and drop support for legacy Xamarin

### ISSUE THREAD

**Issue by chkn** [chkn/Xamarin.SwiftUI#47]
With the recently released preview 7, I think .NET 6 is mature enough to replace the legacy Xamarin project types. This would have some benefits:

- We could remove some build hacks, making things simpler and easier to maintain going forward.
- We would be able to take advantage of new runtime improvements, like function pointers and virtual static members in interfaces.
- Simpler testing/support matrix

Given the early phase of development we're in, I don't really see any downsides to this.

**Comment by chucker** [comment]
https://github.com/xamarin/Xamarin.Legacy.Sdk might also be useful here.

(I'm mostly interested in this project for MAUI, and it seems I need to add `net6.0-ios;net6.0-maccatalyst` tfms, but I'm not sure about all the changes required to the `build.proj`.)

**Comment by vhugogarcia** [comment]
Is it possible to use SwiftUI on MAUI? I think that will bring benefits to create WatchOS application on Swift and then from there embedded them into MAUI somehow?

Maybe something like flutter: https://docs.flutter.dev/development/platform-integration/apple-watch, they don't support it neither, but allow to embedded the SwiftUI on their app.
